"""Add user tables

Revision ID: 7f924896221c
Revises: 143f98fa16fc
Create Date: 2025-09-02 15:34:16.531120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f924896221c'
down_revision = '143f98fa16fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('owner_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('service_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('experience', sa.VARCHAR(length=100), nullable=True),
    sa.Column('website', sa.VARCHAR(length=120), nullable=True),
    sa.Column('instagram', sa.VARCHAR(length=120), nullable=True),
    sa.Column('facebook', sa.VARCHAR(length=120), nullable=True),
    sa.Column('twitter', sa.VARCHAR(length=120), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('total_reviews', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
